DELETE FROM feedback;

INSERT INTO feedback (id, source, content, sentiment, category, created_at, analyzed_at) VALUES
-- POSITIVE FEEDBACK (Praise & Success Stories)
('f001', 'survey', 'Absolutely love the new dashboard redesign! It''s so much easier to navigate now and the loading times are incredibly fast. Great job team!', 'positive', 'praise', datetime('now', '-2 hours'), datetime('now', '-2 hours')),
('f004', 'social', 'Just switched from a competitor and WOW the difference is night and day. Everything just works smoothly. Highly recommend!', 'positive', 'praise', datetime('now', '-5 hours'), datetime('now', '-5 hours')),
('f006', 'email', 'I''ve been a customer for 3 years and the service has been consistently excellent. The support team always responds within hours.', 'positive', 'praise', datetime('now', '-7 hours'), datetime('now', '-7 hours')),
('f010', 'email', 'Thank you for the quick resolution to my billing issue. Sarah from support was incredibly helpful and professional.', 'positive', 'praise', datetime('now', '-11 hours'), datetime('now', '-11 hours')),
('f016', 'social', 'Best customer service I''ve ever experienced! They went above and beyond to help me migrate my data.', 'positive', 'praise', datetime('now', '-17 hours'), datetime('now', '-17 hours')),
('f020', 'social', 'Just discovered your product and I''m blown away by how intuitive it is. Didn''t even need to read the docs!', 'positive', 'praise', datetime('now', '-21 hours'), datetime('now', '-21 hours')),
('f022', 'email', 'The onboarding tutorial was really helpful. Made it easy to get started without feeling overwhelmed.', 'positive', 'praise', datetime('now', '-23 hours'), datetime('now', '-23 hours')),
('f025', 'survey', 'The collaboration features are fantastic! Being able to work on documents simultaneously with my team has transformed how we work.', 'positive', 'praise', datetime('now', '-26 hours'), datetime('now', '-26 hours')),
('f028', 'social', 'Renewed my subscription for another year. Solid product that keeps getting better with each update.', 'positive', 'praise', datetime('now', '-29 hours'), datetime('now', '-29 hours')),
('f030', 'email', 'The calendar sync feature is amazing! Finally all my schedules are in one place.', 'positive', 'praise', datetime('now', '-31 hours'), datetime('now', '-31 hours')),
('f033', 'survey', 'Your product literally saved my business. The automation features have freed up so much of my time.', 'positive', 'praise', datetime('now', '-34 hours'), datetime('now', '-34 hours')),
('f036', 'social', 'The free tier is surprisingly generous. Testing it out before committing to paid and impressed so far.', 'positive', 'praise', datetime('now', '-37 hours'), datetime('now', '-37 hours')),
('f038', 'email', 'Just wanted to say the redesigned logo looks great! Small thing but shows you care about details.', 'positive', 'praise', datetime('now', '-39 hours'), datetime('now', '-39 hours')),
('f041', 'survey', 'Rock solid reliability. Haven''t experienced a single outage in over a year of daily use.', 'positive', 'praise', datetime('now', '-42 hours'), datetime('now', '-42 hours')),
('f044', 'social', 'Switched my whole team over from the competitor. Best decision we made this year!', 'positive', 'praise', datetime('now', '-45 hours'), datetime('now', '-45 hours')),
('f046', 'email', 'The analytics dashboard is incredibly insightful. Love being able to track everything in real-time.', 'positive', 'praise', datetime('now', '-47 hours'), datetime('now', '-47 hours')),
('f049', 'survey', 'Documentation is excellent. Every question I had was answered in the help center.', 'positive', 'praise', datetime('now', '-50 hours'), datetime('now', '-50 hours')),

-- NEGATIVE FEEDBACK - BUGS (Critical Issues)
('f002', 'email', 'The app keeps crashing every time I try to upload a file larger than 10MB. This is really frustrating as I need to upload reports daily for my work.', 'negative', 'bug', datetime('now', '-3 hours'), datetime('now', '-3 hours')),
('f007', 'support_ticket', 'Getting error code 500 when trying to access my account settings. Tried different browsers but same issue persists.', 'negative', 'bug', datetime('now', '-8 hours'), datetime('now', '-8 hours')),
('f011', 'support_ticket', 'The two-factor authentication isn''t working. I''m not receiving the SMS codes even though my phone number is correct.', 'negative', 'bug', datetime('now', '-12 hours'), datetime('now', '-12 hours')),
('f017', 'survey', 'The search functionality is broken. It returns completely irrelevant results and sometimes doesn''t find items I know exist.', 'negative', 'bug', datetime('now', '-18 hours'), datetime('now', '-18 hours')),
('f021', 'survey', 'Loading times have gotten progressively worse over the past few months. What used to take 2 seconds now takes 10+.', 'negative', 'bug', datetime('now', '-22 hours'), datetime('now', '-22 hours')),
('f023', 'support_ticket', 'I''m seeing duplicate entries appearing in my reports. This is causing major issues with our accounting.', 'negative', 'bug', datetime('now', '-24 hours'), datetime('now', '-24 hours')),
('f031', 'support_ticket', 'Images are not loading in the preview. Just showing broken image icons everywhere.', 'negative', 'bug', datetime('now', '-32 hours'), datetime('now', '-32 hours')),
('f037', 'survey', 'Please fix the memory leaks. After a few hours of use, the browser tab is consuming 2GB+ of RAM.', 'negative', 'bug', datetime('now', '-38 hours'), datetime('now', '-38 hours')),
('f039', 'support_ticket', 'The export feature keeps timing out for large datasets. Need this fixed urgently for a client deadline.', 'negative', 'bug', datetime('now', '-40 hours'), datetime('now', '-40 hours')),
('f043', 'support_ticket', 'Audio in video calls is choppy and keeps cutting out. Makes meetings very frustrating.', 'negative', 'bug', datetime('now', '-44 hours'), datetime('now', '-44 hours')),
('f047', 'support_ticket', 'Password reset emails are taking over 30 minutes to arrive. Had to reset twice and wait forever both times.', 'negative', 'bug', datetime('now', '-48 hours'), datetime('now', '-48 hours')),

-- NEGATIVE FEEDBACK - COMPLAINTS (User Dissatisfaction)
('f005', 'survey', 'The mobile app is basically unusable. Buttons are too small, text is cut off, and it drains my battery like crazy. Please fix this.', 'negative', 'complaint', datetime('now', '-6 hours'), datetime('now', '-6 hours')),
('f008', 'social', 'The new pricing is outrageous. You''ve essentially doubled the cost while removing features. Very disappointed in this direction.', 'negative', 'complaint', datetime('now', '-9 hours'), datetime('now', '-9 hours')),
('f015', 'support_ticket', 'Why did you remove the bulk edit feature? This was essential for my workflow and now I have to edit items one by one.', 'negative', 'complaint', datetime('now', '-16 hours'), datetime('now', '-16 hours')),
('f026', 'email', 'Why is there no undo button?? I just made a change that I can''t reverse and lost hours of work.', 'negative', 'complaint', datetime('now', '-27 hours'), datetime('now', '-27 hours')),
('f027', 'support_ticket', 'The notifications are way too aggressive. I''m getting emails for every tiny thing even though I tried adjusting settings.', 'negative', 'complaint', datetime('now', '-28 hours'), datetime('now', '-28 hours')),
('f034', 'email', 'Very unhappy with the recent update. You changed the entire layout and now I can''t find anything.', 'negative', 'complaint', datetime('now', '-35 hours'), datetime('now', '-35 hours')),
('f042', 'email', 'The permission system is confusing. I can''t figure out how to give view-only access to external partners.', 'negative', 'complaint', datetime('now', '-43 hours'), datetime('now', '-43 hours')),
('f050', 'email', 'Terrible experience trying to get a refund. Took 3 weeks and multiple emails to resolve.', 'negative', 'complaint', datetime('now', '-51 hours'), datetime('now', '-51 hours')),

-- NEUTRAL FEEDBACK - FEATURE REQUESTS
('f009', 'survey', 'It would be great if you could add dark mode. I work late nights and the bright white interface is hard on my eyes.', 'neutral', 'feature_request', datetime('now', '-10 hours'), datetime('now', '-10 hours')),
('f012', 'social', 'Can you please add integration with Slack? Would make our team workflow so much better.', 'neutral', 'feature_request', datetime('now', '-13 hours'), datetime('now', '-13 hours')),
('f014', 'email', 'I accidentally deleted important files and there''s no way to recover them. You really need a trash/recycle bin feature!', 'negative', 'feature_request', datetime('now', '-15 hours'), datetime('now', '-15 hours')),
('f018', 'email', 'Would love to see keyboard shortcuts added. Power users like me would really benefit from this.', 'neutral', 'feature_request', datetime('now', '-19 hours'), datetime('now', '-19 hours')),
('f024', 'social', 'Please add support for more languages. Many of my team members don''t speak English fluently.', 'neutral', 'feature_request', datetime('now', '-25 hours'), datetime('now', '-25 hours')),
('f032', 'social', 'Would be perfect if you added a native Windows app instead of just the web version.', 'neutral', 'feature_request', datetime('now', '-33 hours'), datetime('now', '-33 hours')),
('f040', 'social', 'Integration with Google Drive would be a game changer. Please consider adding this!', 'neutral', 'feature_request', datetime('now', '-41 hours'), datetime('now', '-41 hours')),
('f048', 'social', 'Can we please get an offline mode? I travel a lot and losing connectivity kills my productivity.', 'neutral', 'feature_request', datetime('now', '-49 hours'), datetime('now', '-49 hours')),

-- NEUTRAL FEEDBACK - QUESTIONS
('f003', 'support_ticket', 'Is there any way to export my data to CSV format? I couldn''t find this option anywhere in the settings.', 'neutral', 'question', datetime('now', '-4 hours'), datetime('now', '-4 hours')),
('f019', 'support_ticket', 'The API rate limits are too restrictive for our use case. Is there an enterprise plan with higher limits?', 'neutral', 'question', datetime('now', '-20 hours'), datetime('now', '-20 hours')),
('f035', 'support_ticket', 'How do I cancel my subscription? I''ve been looking for 20 minutes and can''t find the option anywhere.', 'negative', 'question', datetime('now', '-36 hours'), datetime('now', '-36 hours')),

-- NEUTRAL FEEDBACK - OTHER
('f013', 'survey', 'The product does what it says. Nothing special but nothing wrong either. Gets the job done.', 'neutral', 'other', datetime('now', '-14 hours'), datetime('now', '-14 hours')),
('f029', 'survey', 'It''s fine I guess. Does what I need but the interface feels dated compared to alternatives.', 'neutral', 'other', datetime('now', '-30 hours'), datetime('now', '-30 hours')),
('f045', 'survey', 'Average product. Not bad but not great either. Might look at alternatives when our contract is up.', 'neutral', 'other', datetime('now', '-46 hours'), datetime('now', '-46 hours')),

-- ADDITIONAL ENTRIES TO REACH 200+ (Similar themes for clustering analysis)
-- More Bug Reports (Similar to existing bugs)
('f051', 'support_ticket', 'App crashes when uploading files over 5MB. Same issue as others have reported.', 'negative', 'bug', datetime('now', '-52 hours'), datetime('now', '-52 hours')),
('f052', 'email', 'Getting constant 500 errors. Can''t access my dashboard at all today.', 'negative', 'bug', datetime('now', '-53 hours'), datetime('now', '-53 hours')),
('f053', 'survey', 'File upload is completely broken. Tried multiple times with different file sizes.', 'negative', 'bug', datetime('now', '-54 hours'), datetime('now', '-54 hours')),
('f054', 'support_ticket', '2FA SMS codes never arrive. This is a security issue that needs immediate attention.', 'negative', 'bug', datetime('now', '-55 hours'), datetime('now', '-55 hours')),
('f055', 'email', 'Two-factor auth is broken. Not getting any verification texts.', 'negative', 'bug', datetime('now', '-56 hours'), datetime('now', '-56 hours')),
('f056', 'survey', 'Search returns wrong results. Typed exact filename and it didn''t show up.', 'negative', 'bug', datetime('now', '-57 hours'), datetime('now', '-57 hours')),
('f057', 'support_ticket', 'Search feature is completely useless. Never finds what I''m looking for.', 'negative', 'bug', datetime('now', '-58 hours'), datetime('now', '-58 hours')),
('f058', 'email', 'Performance has degraded significantly. Everything is so slow now.', 'negative', 'bug', datetime('now', '-59 hours'), datetime('now', '-59 hours')),
('f059', 'survey', 'Page load times are unacceptable. Takes forever to load anything.', 'negative', 'bug', datetime('now', '-60 hours'), datetime('now', '-60 hours')),
('f060', 'support_ticket', 'Seeing duplicate data in all my reports. Makes them completely unreliable.', 'negative', 'bug', datetime('now', '-61 hours'), datetime('now', '-61 hours')),
('f061', 'email', 'Reports showing duplicate entries. Is this a known issue?', 'negative', 'bug', datetime('now', '-62 hours'), datetime('now', '-62 hours')),
('f062', 'survey', 'Images won''t load. Just see placeholder icons everywhere.', 'negative', 'bug', datetime('now', '-63 hours'), datetime('now', '-63 hours')),
('f063', 'support_ticket', 'All images are broken in the app. Can''t view any visual content.', 'negative', 'bug', datetime('now', '-64 hours'), datetime('now', '-64 hours')),
('f064', 'email', 'Memory usage keeps climbing until my browser freezes.', 'negative', 'bug', datetime('now', '-65 hours'), datetime('now', '-65 hours')),
('f065', 'survey', 'Browser tab uses insane amounts of memory. Had to restart multiple times today.', 'negative', 'bug', datetime('now', '-66 hours'), datetime('now', '-66 hours')),
('f066', 'support_ticket', 'Export times out every single time with our dataset size.', 'negative', 'bug', datetime('now', '-67 hours'), datetime('now', '-67 hours')),
('f067', 'email', 'Can''t export large reports. Always fails halfway through.', 'negative', 'bug', datetime('now', '-68 hours'), datetime('now', '-68 hours')),
('f068', 'survey', 'Video call audio quality is terrible. Constant dropouts and lag.', 'negative', 'bug', datetime('now', '-69 hours'), datetime('now', '-69 hours')),
('f069', 'support_ticket', 'Video calls are unusable. Audio keeps cutting in and out.', 'negative', 'bug', datetime('now', '-70 hours'), datetime('now', '-70 hours')),
('f070', 'email', 'Password reset takes forever. Waited 45 minutes for the email.', 'negative', 'bug', datetime('now', '-71 hours'), datetime('now', '-71 hours')),

-- More Complaints (Similar themes)
('f071', 'survey', 'Mobile app is completely broken. Can''t do anything on my phone.', 'negative', 'complaint', datetime('now', '-72 hours'), datetime('now', '-72 hours')),
('f072', 'email', 'Mobile experience is awful. Everything is broken or too small to click.', 'negative', 'complaint', datetime('now', '-73 hours'), datetime('now', '-73 hours')),
('f073', 'social', 'New pricing structure is ridiculous. Paying more for less features.', 'negative', 'complaint', datetime('now', '-74 hours'), datetime('now', '-74 hours')),
('f074', 'survey', 'Price increase is unjustified. You removed features but charge more??', 'negative', 'complaint', datetime('now', '-75 hours'), datetime('now', '-75 hours')),
('f075', 'support_ticket', 'Bulk edit removal has destroyed my productivity. Why would you do this?', 'negative', 'complaint', datetime('now', '-76 hours'), datetime('now', '-76 hours')),
('f076', 'email', 'Removing bulk actions was a huge mistake. Now everything takes 10x longer.', 'negative', 'complaint', datetime('now', '-77 hours'), datetime('now', '-77 hours')),
('f077', 'survey', 'No undo functionality is insane in 2026. Lost so much work today.', 'negative', 'complaint', datetime('now', '-78 hours'), datetime('now', '-78 hours')),
('f078', 'support_ticket', 'Desperately need an undo feature. Made a mistake and can''t revert it.', 'negative', 'complaint', datetime('now', '-79 hours'), datetime('now', '-79 hours')),
('f079', 'email', 'Getting bombarded with notification emails. Can''t turn them off properly.', 'negative', 'complaint', datetime('now', '-80 hours'), datetime('now', '-80 hours')),
('f080', 'survey', 'Notification settings don''t work. Still getting emails for everything.', 'negative', 'complaint', datetime('now', '-81 hours'), datetime('now', '-81 hours')),
('f081', 'social', 'UI redesign is horrible. Can''t find anything anymore.', 'negative', 'complaint', datetime('now', '-82 hours'), datetime('now', '-82 hours')),
('f082', 'support_ticket', 'New interface is confusing. Why change what was working fine?', 'negative', 'complaint', datetime('now', '-83 hours'), datetime('now', '-83 hours')),
('f083', 'email', 'Permissions are way too complicated. Just want to share view-only access.', 'negative', 'complaint', datetime('now', '-84 hours'), datetime('now', '-84 hours')),
('f084', 'survey', 'Permission system makes no sense. Documentation doesn''t help either.', 'negative', 'complaint', datetime('now', '-85 hours'), datetime('now', '-85 hours')),
('f085', 'support_ticket', 'Refund process is a nightmare. Still waiting after 2 weeks.', 'negative', 'complaint', datetime('now', '-86 hours'), datetime('now', '-86 hours')),

-- More Feature Requests (Similar themes)
('f086', 'survey', 'Really need dark mode. Current theme hurts my eyes.', 'neutral', 'feature_request', datetime('now', '-87 hours'), datetime('now', '-87 hours')),
('f087', 'email', 'Dark theme please! Working late is painful with all this white.', 'neutral', 'feature_request', datetime('now', '-88 hours'), datetime('now', '-88 hours')),
('f088', 'social', 'Slack integration would be perfect for our workflow.', 'neutral', 'feature_request', datetime('now', '-89 hours'), datetime('now', '-89 hours')),
('f089', 'survey', 'Need Slack notifications. Would make team collaboration much easier.', 'neutral', 'feature_request', datetime('now', '-90 hours'), datetime('now', '-90 hours')),
('f090', 'support_ticket', 'Trash/recycle bin is essential. Accidentally deleted important files.', 'negative', 'feature_request', datetime('now', '-91 hours'), datetime('now', '-91 hours')),
('f091', 'email', 'Please add a recycle bin. Too easy to permanently delete things.', 'neutral', 'feature_request', datetime('now', '-92 hours'), datetime('now', '-92 hours')),
('f092', 'survey', 'Keyboard shortcuts would speed up my workflow tremendously.', 'neutral', 'feature_request', datetime('now', '-93 hours'), datetime('now', '-93 hours')),
('f093', 'social', 'Power users need keyboard shortcuts. Mouse navigation is too slow.', 'neutral', 'feature_request', datetime('now', '-94 hours'), datetime('now', '-94 hours')),
('f094', 'email', 'Multi-language support is critical for our international team.', 'neutral', 'feature_request', datetime('now', '-95 hours'), datetime('now', '-95 hours')),
('f095', 'survey', 'Need Spanish and French translations. Half our team doesn''t speak English.', 'neutral', 'feature_request', datetime('now', '-96 hours'), datetime('now', '-96 hours')),
('f096', 'support_ticket', 'Native desktop app would be so much better than web version.', 'neutral', 'feature_request', datetime('now', '-97 hours'), datetime('now', '-97 hours')),
('f097', 'social', 'Windows desktop client please! Browser version is limiting.', 'neutral', 'feature_request', datetime('now', '-98 hours'), datetime('now', '-98 hours')),
('f098', 'email', 'Google Drive integration is a must-have for us.', 'neutral', 'feature_request', datetime('now', '-99 hours'), datetime('now', '-99 hours')),
('f099', 'survey', 'Please integrate with Google Workspace. Would complete our stack.', 'neutral', 'feature_request', datetime('now', '-100 hours'), datetime('now', '-100 hours')),
('f100', 'support_ticket', 'Offline mode is essential for my use case. Travel frequently.', 'neutral', 'feature_request', datetime('now', '-101 hours'), datetime('now', '-101 hours')),

-- More Positive Feedback
('f101', 'survey', 'Dashboard is incredibly intuitive. Love the new design!', 'positive', 'praise', datetime('now', '-102 hours'), datetime('now', '-102 hours')),
('f102', 'email', 'New UI is amazing. Everything feels so much faster and cleaner.', 'positive', 'praise', datetime('now', '-103 hours'), datetime('now', '-103 hours')),
('f103', 'social', 'Best tool in this category. Tried all competitors and you''re way ahead.', 'positive', 'praise', datetime('now', '-104 hours'), datetime('now', '-104 hours')),
('f104', 'survey', 'Switching from competitor was the best decision. No comparison.', 'positive', 'praise', datetime('now', '-105 hours'), datetime('now', '-105 hours')),
('f105', 'email', 'Support team is phenomenal. Always quick and helpful responses.', 'positive', 'praise', datetime('now', '-106 hours'), datetime('now', '-106 hours')),
('f106', 'support_ticket', 'Thank you for the excellent support! Issue resolved in minutes.', 'positive', 'praise', datetime('now', '-107 hours'), datetime('now', '-107 hours')),
('f107', 'social', 'Customer service is top-notch. They really care about users.', 'positive', 'praise', datetime('now', '-108 hours'), datetime('now', '-108 hours')),
('f108', 'survey', 'Migration support was incredible. Made switching painless.', 'positive', 'praise', datetime('now', '-109 hours'), datetime('now', '-109 hours')),
('f109', 'email', 'So easy to use! Didn''t need any training to get started.', 'positive', 'praise', datetime('now', '-110 hours'), datetime('now', '-110 hours')),
('f110', 'social', 'Interface is self-explanatory. Very well designed product.', 'positive', 'praise', datetime('now', '-111 hours'), datetime('now', '-111 hours')),
('f111', 'survey', 'Onboarding was smooth and helpful. Got up to speed quickly.', 'positive', 'praise', datetime('now', '-112 hours'), datetime('now', '-112 hours')),
('f112', 'email', 'Tutorial videos were super helpful. Great learning resources.', 'positive', 'praise', datetime('now', '-113 hours'), datetime('now', '-113 hours')),
('f113', 'support_ticket', 'Real-time collaboration is game-changing. Team loves it.', 'positive', 'praise', datetime('now', '-114 hours'), datetime('now', '-114 hours')),
('f114', 'social', 'Team features are excellent. Working together is seamless now.', 'positive', 'praise', datetime('now', '-115 hours'), datetime('now', '-115 hours')),
('f115', 'survey', 'Annual renewal was a no-brainer. Product keeps improving.', 'positive', 'praise', datetime('now', '-116 hours'), datetime('now', '-116 hours')),
('f116', 'email', 'Happy to renew subscription. Great value for money.', 'positive', 'praise', datetime('now', '-117 hours'), datetime('now', '-117 hours')),
('f117', 'social', 'Calendar sync is brilliant. Everything in one place finally.', 'positive', 'praise', datetime('now', '-118 hours'), datetime('now', '-118 hours')),
('f118', 'survey', 'Integration features are perfect. Connects with all our tools.', 'positive', 'praise', datetime('now', '-119 hours'), datetime('now', '-119 hours')),
('f119', 'email', 'Automation saved our business. Can''t imagine going back.', 'positive', 'praise', datetime('now', '-120 hours'), datetime('now', '-120 hours')),
('f120', 'support_ticket', 'Workflow automation is incredible. Saves hours every week.', 'positive', 'praise', datetime('now', '-121 hours'), datetime('now', '-121 hours')),
('f121', 'social', 'Free tier is generous. Great way to try before buying.', 'positive', 'praise', datetime('now', '-122 hours'), datetime('now', '-122 hours')),
('f122', 'survey', 'Trial period was perfect for evaluating. Now a paying customer.', 'positive', 'praise', datetime('now', '-123 hours'), datetime('now', '-123 hours')),
('f123', 'email', 'Love the attention to detail. Even small things are polished.', 'positive', 'praise', datetime('now', '-124 hours'), datetime('now', '-124 hours')),
('f124', 'social', 'Quality is evident in every feature. Very well built.', 'positive', 'praise', datetime('now', '-125 hours'), datetime('now', '-125 hours')),
('f125', 'survey', 'Never had downtime. Reliability is outstanding.', 'positive', 'praise', datetime('now', '-126 hours'), datetime('now', '-126 hours')),
('f126', 'email', '99.9% uptime in my experience. Very stable platform.', 'positive', 'praise', datetime('now', '-127 hours'), datetime('now', '-127 hours')),
('f127', 'support_ticket', 'Migrated entire company. Everyone is happy with the switch.', 'positive', 'praise', datetime('now', '-128 hours'), datetime('now', '-128 hours')),
('f128', 'social', 'Convinced my team to switch. No regrets whatsoever.', 'positive', 'praise', datetime('now', '-129 hours'), datetime('now', '-129 hours')),
('f129', 'survey', 'Analytics are comprehensive and easy to understand.', 'positive', 'praise', datetime('now', '-130 hours'), datetime('now', '-130 hours')),
('f130', 'email', 'Reporting features are exactly what we needed. Very powerful.', 'positive', 'praise', datetime('now', '-131 hours'), datetime('now', '-131 hours')),
('f131', 'social', 'Documentation is thorough and well-written.', 'positive', 'praise', datetime('now', '-132 hours'), datetime('now', '-132 hours')),
('f132', 'survey', 'Help docs are amazing. Found answers to all my questions.', 'positive', 'praise', datetime('now', '-133 hours'), datetime('now', '-133 hours')),

-- More Questions
('f133', 'support_ticket', 'How do I export to Excel? Can''t find the option.', 'neutral', 'question', datetime('now', '-134 hours'), datetime('now', '-134 hours')),
('f134', 'email', 'Is there a way to batch import data? Need to migrate from old system.', 'neutral', 'question', datetime('now', '-135 hours'), datetime('now', '-135 hours')),
('f135', 'survey', 'What are the API limits on the free plan?', 'neutral', 'question', datetime('now', '-136 hours'), datetime('now', '-136 hours')),
('f136', 'support_ticket', 'Do you offer enterprise pricing for teams over 100 users?', 'neutral', 'question', datetime('now', '-137 hours'), datetime('now', '-137 hours')),
('f137', 'email', 'Where is the account deletion option? Can''t find it anywhere.', 'neutral', 'question', datetime('now', '-138 hours'), datetime('now', '-138 hours')),
('f138', 'social', 'How do I downgrade my plan? Current tier is more than I need.', 'neutral', 'question', datetime('now', '-139 hours'), datetime('now', '-139 hours')),
('f139', 'survey', 'Is there a student discount available?', 'neutral', 'question', datetime('now', '-140 hours'), datetime('now', '-140 hours')),
('f140', 'support_ticket', 'Can I transfer my account to a different email address?', 'neutral', 'question', datetime('now', '-141 hours'), datetime('now', '-141 hours')),
('f141', 'email', 'What''s the difference between Pro and Enterprise plans?', 'neutral', 'question', datetime('now', '-142 hours'), datetime('now', '-142 hours')),
('f142', 'social', 'Do you offer non-profit pricing? We''re a registered charity.', 'neutral', 'question', datetime('now', '-143 hours'), datetime('now', '-143 hours')),

-- More Neutral/Mixed Feedback
('f143', 'survey', 'It''s okay. Does the basics but nothing impressive.', 'neutral', 'other', datetime('now', '-144 hours'), datetime('now', '-144 hours')),
('f144', 'email', 'Decent product. Works as advertised but could be better.', 'neutral', 'other', datetime('now', '-145 hours'), datetime('now', '-145 hours')),
('f145', 'social', 'Good but not great. Competitors have caught up.', 'neutral', 'other', datetime('now', '-146 hours'), datetime('now', '-146 hours')),
('f146', 'survey', 'Solid but unexciting. Gets the job done though.', 'neutral', 'other', datetime('now', '-147 hours'), datetime('now', '-147 hours')),
('f147', 'email', 'Average experience. Nothing to complain about, nothing to rave about.', 'neutral', 'other', datetime('now', '-148 hours'), datetime('now', '-148 hours')),
('f148', 'support_ticket', 'Meets basic requirements. Would like to see more innovation.', 'neutral', 'other', datetime('now', '-149 hours'), datetime('now', '-149 hours')),
('f149', 'social', 'It works. That''s about all I can say.', 'neutral', 'other', datetime('now', '-150 hours'), datetime('now', '-150 hours')),
('f150', 'survey', 'Functional but feels dated. UI needs modernization.', 'neutral', 'other', datetime('now', '-151 hours'), datetime('now', '-151 hours')),

-- Additional varied feedback
('f151', 'email', 'Performance is great on desktop but mobile needs work.', 'neutral', 'other', datetime('now', '-152 hours'), datetime('now', '-152 hours')),
('f152', 'survey', 'Love the features but the pricing is a bit steep.', 'neutral', 'other', datetime('now', '-153 hours'), datetime('now', '-153 hours')),
('f153', 'support_ticket', 'API documentation could be more detailed with examples.', 'negative', 'complaint', datetime('now', '-154 hours'), datetime('now', '-154 hours')),
('f154', 'social', 'Security features are robust. Feels safe to use.', 'positive', 'praise', datetime('now', '-155 hours'), datetime('now', '-155 hours')),
('f155', 'email', 'Impressed by the speed improvements in the latest update.', 'positive', 'praise', datetime('now', '-156 hours'), datetime('now', '-156 hours')),
('f156', 'survey', 'Data import process is clunky and error-prone.', 'negative', 'complaint', datetime('now', '-157 hours'), datetime('now', '-157 hours')),
('f157', 'support_ticket', 'Love the mobile app! Use it more than desktop version now.', 'positive', 'praise', datetime('now', '-158 hours'), datetime('now', '-158 hours')),
('f158', 'social', 'Webhook support would be great for our integration needs.', 'neutral', 'feature_request', datetime('now', '-159 hours'), datetime('now', '-159 hours')),
('f159', 'email', 'Billing dashboard is confusing. Hard to understand charges.', 'negative', 'complaint', datetime('now', '-160 hours'), datetime('now', '-160 hours')),
('f160', 'survey', 'Templates feature saved me so much time. Brilliant!', 'positive', 'praise', datetime('now', '-161 hours'), datetime('now', '-161 hours')),
('f161', 'support_ticket', 'Can''t figure out how to set up SSO for my team.', 'neutral', 'question', datetime('now', '-162 hours'), datetime('now', '-162 hours')),
('f162', 'social', 'Version history feature is a lifesaver. Used it multiple times.', 'positive', 'praise', datetime('now', '-163 hours'), datetime('now', '-163 hours')),
('f163', 'email', 'Marketplace integrations are limited. Need more options.', 'negative', 'complaint', datetime('now', '-164 hours'), datetime('now', '-164 hours')),
('f164', 'survey', 'Email notifications are well-designed and informative.', 'positive', 'praise', datetime('now', '-165 hours'), datetime('now', '-165 hours')),
('f165', 'support_ticket', 'Custom fields would make this perfect for our workflow.', 'neutral', 'feature_request', datetime('now', '-166 hours'), datetime('now', '-166 hours')),
('f166', 'social', 'API rate limits feel arbitrary. Can they be increased?', 'negative', 'complaint', datetime('now', '-167 hours'), datetime('now', '-167 hours')),
('f167', 'email', 'Tags and labels system is intuitive and powerful.', 'positive', 'praise', datetime('now', '-168 hours'), datetime('now', '-168 hours')),
('f168', 'survey', 'Bulk operations timeout too quickly with large datasets.', 'negative', 'bug', datetime('now', '-169 hours'), datetime('now', '-169 hours')),
('f169', 'support_ticket', 'Would pay extra for priority support. Current response time is slow.', 'neutral', 'feature_request', datetime('now', '-170 hours'), datetime('now', '-170 hours')),
('f170', 'social', 'Sharing permissions are perfect. Very granular control.', 'positive', 'praise', datetime('now', '-171 hours'), datetime('now', '-171 hours')),
('f171', 'email', 'Dashboard widgets would be nice for customization.', 'neutral', 'feature_request', datetime('now', '-172 hours'), datetime('now', '-172 hours')),
('f172', 'survey', 'Login page sometimes shows errors randomly then works.', 'negative', 'bug', datetime('now', '-173 hours'), datetime('now', '-173 hours')),
('f173', 'support_ticket', 'CSV exports are missing some columns from the UI view.', 'negative', 'bug', datetime('now', '-174 hours'), datetime('now', '-174 hours')),
('f174', 'social', 'Activity feed is super useful for tracking team changes.', 'positive', 'praise', datetime('now', '-175 hours'), datetime('now', '-175 hours')),
('f175', 'email', 'Print layout is broken. Pages cut off in weird places.', 'negative', 'bug', datetime('now', '-176 hours'), datetime('now', '-176 hours')),
('f176', 'survey', 'Training resources helped our team get productive quickly.', 'positive', 'praise', datetime('now', '-177 hours'), datetime('now', '-177 hours')),
('f177', 'support_ticket', 'Archive feature doesn''t seem to work properly.', 'negative', 'bug', datetime('now', '-178 hours'), datetime('now', '-178 hours')),
('f178', 'social', 'Would love to see Zapier integration added.', 'neutral', 'feature_request', datetime('now', '-179 hours'), datetime('now', '-179 hours')),
('f179', 'email', 'Impressed by how quickly you ship new features.', 'positive', 'praise', datetime('now', '-180 hours'), datetime('now', '-180 hours')),
('f180', 'survey', 'Filter options are limited. Need more advanced filtering.', 'negative', 'complaint', datetime('now', '-181 hours'), datetime('now', '-181 hours')),
('f181', 'support_ticket', 'How secure is my data? Any SOC 2 compliance?', 'neutral', 'question', datetime('now', '-182 hours'), datetime('now', '-182 hours')),
('f182', 'social', 'Mobile notifications work perfectly. Never miss important updates.', 'positive', 'praise', datetime('now', '-183 hours'), datetime('now', '-183 hours')),
('f183', 'email', 'Text editor needs more formatting options.', 'neutral', 'feature_request', datetime('now', '-184 hours'), datetime('now', '-184 hours')),
('f184', 'survey', 'Comments and mentions make collaboration easy.', 'positive', 'praise', datetime('now', '-185 hours'), datetime('now', '-185 hours')),
('f185', 'support_ticket', 'File preview doesn''t work for DOCX files.', 'negative', 'bug', datetime('now', '-186 hours'), datetime('now', '-186 hours')),
('f186', 'social', 'Pricing transparency is appreciated. No hidden fees.', 'positive', 'praise', datetime('now', '-187 hours'), datetime('now', '-187 hours')),
('f187', 'email', 'Need better mobile tablet optimization.', 'neutral', 'feature_request', datetime('now', '-188 hours'), datetime('now', '-188 hours')),
('f188', 'survey', 'Guest access feature works great for clients.', 'positive', 'praise', datetime('now', '-189 hours'), datetime('now', '-189 hours')),
('f189', 'support_ticket', 'Time zone handling is buggy. Shows wrong times.', 'negative', 'bug', datetime('now', '-190 hours'), datetime('now', '-190 hours')),
('f190', 'social', 'Multi-select operations would save so much time.', 'neutral', 'feature_request', datetime('now', '-191 hours'), datetime('now', '-191 hours')),
('f191', 'email', 'Update changelog is detailed and helpful. Appreciate the transparency.', 'positive', 'praise', datetime('now', '-192 hours'), datetime('now', '-192 hours')),
('f192', 'survey', 'Font rendering looks blurry on high-DPI displays.', 'negative', 'bug', datetime('now', '-193 hours'), datetime('now', '-193 hours')),
('f193', 'support_ticket', 'Would pay for white-labeling options.', 'neutral', 'feature_request', datetime('now', '-194 hours'), datetime('now', '-194 hours')),
('f194', 'social', 'Quick actions menu is so convenient. Use it constantly.', 'positive', 'praise', datetime('now', '-195 hours'), datetime('now', '-195 hours')),
('f195', 'email', 'Browser extension would be incredibly useful.', 'neutral', 'feature_request', datetime('now', '-196 hours'), datetime('now', '-196 hours')),
('f196', 'survey', 'Impressed by the thoughtful UX design throughout.', 'positive', 'praise', datetime('now', '-197 hours'), datetime('now', '-197 hours')),
('f197', 'support_ticket', 'Copy-paste from Excel doesn''t preserve formatting.', 'negative', 'bug', datetime('now', '-198 hours'), datetime('now', '-198 hours')),
('f198', 'social', 'Saved searches feature is brilliant for repetitive tasks.', 'positive', 'praise', datetime('now', '-199 hours'), datetime('now', '-199 hours')),
('f199', 'email', 'Dashboard takes too long to load on slower connections.', 'negative', 'bug', datetime('now', '-200 hours'), datetime('now', '-200 hours')),
('f200', 'survey', 'Excellent product. Highly recommend to anyone looking in this space.', 'positive', 'praise', datetime('now', '-201 hours'), datetime('now', '-201 hours'));